parameters:
#    clc_parameter.example.class: Clc\ParameterBundle\Example

services:
#    clc_parameter.example:
#        class: %clc_parameter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
