<?php

namespace Clc\ExpensemanagerBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ExpensemanagerController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Clc\ExpensemanagerBundle\Controller\ExpensemanagerController();
        return $instance;
    }
}
