# src/Clc/TodosBundle/Resources/routing.yml

clc_todos_homepage:
    pattern:  /
    defaults: { _controller: ClcTodosBundle:Todos:index }

clc_todos_new:
    pattern: /new
    defaults: { _controller: ClcTodosBundle:Todos:new }