# src/Clc/TodosBundle/Resources/routing.yml

clc_todos_homepage:
    pattern:  /{state}
    defaults: { _controller: ClcTodosBundle:Todos:index }

clc_todos_new:
    pattern: /
    defaults: { _controller: ClcTodosBundle:Todos:new }
    
clc_todos_remove:
    pattern: /remove/{id}
    defaults: { _controller: ClcTodosBundle:Todos:remove }