parameters:
#    clc_todos.example.class: Clc\TodosBundle\Example

services:
#    clc_todos.example:
#        class: %clc_todos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
