<?php

namespace Clc\ExpensemanagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * expenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class expenseRepository extends EntityRepository
{
    public function getByColoc($coloc)
    {
         $q = $this
            ->createQueryBuilder('e')
            ->where('e.coloc = :coloc')
            ->orderBy('e.date', 'ASC')
            ->setParameter('coloc', $coloc)
            ->getQuery();

         return $q->getResult();
    }
    
    public function getNumber()
    {
        
    }
}
