<?php

namespace Clc\ExpensemanagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * expenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class expenseRepository extends EntityRepository
{
}
