<?php

namespace Clc\ExpensemanagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * paybackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paybackRepository extends EntityRepository
{
}
