<?php

namespace Clc\InboxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * notificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notificationRepository extends EntityRepository
{
}
