parameters:
#    clc_event.example.class: Clc\EventBundle\Example

services:
#    clc_event.example:
#        class: %clc_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
