# src/Clc/ColocBundle/Resources/config/routing.yml

clc_coloc_homepage:
    pattern: /
    defaults: { _controller: ClcColocBundle:Coloc:index }

clc_coloc_new:
    pattern: /new
    defaults: { _controller: ClcColocBundle:Coloc:new }
    
clc_coloc_leave_flatshare:
    pattern: /leave
    defaults: { _controller: ClcColocBundle:Coloc:leaveFlatshare }
    
clc_coloc_new_invitation:
    pattern: /send/invitation
    defaults: { _controller: ClcColocBundle:Invitation:sendInvitation }
    
clc_coloc_accept_invitation:
    pattern: /accept/{id}
    defaults: { _controller: ClcColocBundle:Invitation:acceptInvitation } 