# src/Clc/ColocBundle/Resources/config/routing.yml

clc_coloc_homepage:
    pattern: /
    defaults: { _controller: ClcColocBundle:Coloc:index }

clc_coloc_new:
    pattern: /new
    defaults: { _controller: ClcColocBundle:Coloc:new }
    
clc_coloc_edit:
    pattern: /edit
    defaults: { _controller: ClcColocBundle:Coloc:edit }
    
clc_coloc_leave_flatshare:
    pattern: /leave
    defaults: { _controller: ClcColocBundle:Coloc:leaveFlatshare }
    
clc_coloc_new_invitation:
    pattern: /send/invitation
    defaults: { _controller: ClcColocBundle:Invitation:sendInvitation }

clc_coloc_invite_flatmates:
    pattern: /invite
    defaults: { _controller: ClcColocBundle:Invitation:inviteFlatmates }
    
clc_coloc_accept_invitation:
    pattern: /accept/{id}
    defaults: { _controller: ClcColocBundle:Invitation:acceptInvitation }
    
clc_coloc_remove_invitation:
    pattern: /remove/{id}
    defaults: { _controller: ClcColocBundle:Invitation:removeInvitation }

clc_coloc_refuse_invitation:
    pattern: /refuse/{id}
    defaults: { _controller: ClcColocBundle:Invitation:refuseInvitation }
    
clc_coloc_statistics:
    pattern: /statistics
    defaults: { _controller: ClcColocBundle:Statistics:index }
  
clc_coloc_statistics_feedback:
    pattern: /statistics/feedback
    defaults: { _controller: ClcColocBundle:Statistics:feedback }

clc_coloc_generate_tokens:
    pattern: /generate/tokens
    defaults: { _controller: ClcColocBundle:Coloc:generateAllTokens }