parameters:
#    clc_coloc.example.class: Clc\ColocBundle\Example

services:
#    clc_coloc.example:
#        class: %clc_coloc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
