<?php

namespace Clc\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * feedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class feedbackRepository extends EntityRepository
{
}
