<?php

namespace Clc\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * profilepictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profilepictureRepository extends EntityRepository
{
}
