<?php

namespace Clc\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * profile_pictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profile_pictureRepository extends EntityRepository
{
}
