<?php

namespace Clc\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUserWithMyActiveExpenses()
    {
        $qb = $this->createQueryBuilder('u')
             ->leftJoin('u.myexpenses', 'e')
             ->with('e.active = true')   
             ->addSelect('e');
 
    try {
        return $qb->getQuery()->getResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
    }
    
    public function getUserWithForMeActiveExpenses()
    {
        
    }
}
