parameters:
#    clc_admin.example.class: Clc\AdminBundle\Example

services:
    sonata.admin.feedback:
        class: Clc\AdminBundle\Admin\feedback
        tags:
            - { name: sonata.admin, manager_type: orm, group: UserBundle, label: "Feedbacks" }
        arguments:
            - ~
            - Clc\UserBundle\Entity\feedback
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ClcAdminBundle]]
            
    sonata.admin.User:
        class: Clc\AdminBundle\Admin\User
        tags:
            - { name: sonata.admin, manager_type: orm, group: UserBundle, label: "Users" }
        arguments:
            - ~
            - Clc\UserBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ClcAdminBundle]]
            
    sonata.admin.coloc:
        class: Clc\AdminBundle\Admin\coloc
        tags:
            - { name: sonata.admin, manager_type: orm, group: ColocBundle, label: "Colocs" }
        arguments:
            - ~
            - Clc\ColocBundle\Entity\coloc
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ClcAdminBundle]]

    sonata.admin.invitation:
        class: Clc\AdminBundle\Admin\invitation
        tags:
            - { name: sonata.admin, manager_type: orm, group: ColocBundle, label: "Pending invitations" }
        arguments:
            - ~
            - Clc\ColocBundle\Entity\invitation
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ClcAdminBundle]]

    sonata.admin.expense:
        class: Clc\AdminBundle\Admin\expense
        tags:
            - { name: sonata.admin, manager_type: orm, group: Items, label: "Expenses" }
        arguments:
            - ~
            - Clc\ExpensemanagerBundle\Entity\expense
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ClcAdminBundle]]
            
    sonata.admin.task:
        class: Clc\AdminBundle\Admin\task
        tags:
            - { name: sonata.admin, manager_type: orm, group: Items, label: "To-dos" }
        arguments:
            - ~
            - Clc\TodosBundle\Entity\task
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ClcAdminBundle]]
        
    sonata.admin.item:
        class: Clc\AdminBundle\Admin\item
        tags:
            - { name: sonata.admin, manager_type: orm, group: Items, label: "Shopping items" }
        arguments:
            - ~
            - Clc\ShoppinglistBundle\Entity\item
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ClcAdminBundle]]
            
    sonata.admin.notification:
        class: Clc\AdminBundle\Admin\notification
        tags:
            - { name: sonata.admin, manager_type: orm, group: Other, label: "Notifications" }
        arguments:
            - ~
            - Clc\InboxBundle\Entity\notification
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ClcAdminBundle]]
            