parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     
    database_name:     colocall_main
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    api_facebook_id:      431921740237367 # ID de l’application/Clé de l’API
    api_facebook_secret:  f4a9575bce51fbcf4f6dc18617b74a9d # Clé secrète
    api_facebook_name:    http://apps.facebook.com/colocall/ # App Namespace
    api_facebook_server:  http://localhost:8888/colocall/web/app_dev.php/ # URL du site
