root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /{_locale}/
        permanent: true

clc_welcome:
    resource: "@ClcWelcomeBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr

clc_user:
    resource: "@ClcUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/user
    requirements:
        _locale: en|fr

clc_parameters:
    resource: "@ClcParametersBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/parameters
    requirements:
        _locale: en|fr

clc_coloc:
    resource: "@ClcColocBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/coloc
    requirements:
        _locale: en|fr

clc_dashboard:
    resource: "@ClcDashboardBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr

clc_inbox:
    resource: "@ClcInboxBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/inbox
    requirements:
        _locale: en|fr

clc_event:
    resource: "@ClcEventBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/event
    requirements:
        _locale: en|fr

clc_shoppinglist:
    resource: "@ClcShoppinglistBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/shoppinglist
    requirements:
        _locale: en|fr

clc_todos:
    resource: "@ClcTodosBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/todos
    requirements:
        _locale: en|fr

clc_expensemanager:
    resource: "@ClcExpensemanagerBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/expensemanager/
    requirements:
        _locale: en|fr

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

_security_check:
    pattern:  /{_locale}/login_facebook_check
    requirements:
        _locale: en|fr

_security_logout:
    pattern:  /{_locale}/logout
    requirements:
        _locale: en|fr

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /{_locale}/admin
    requirements:
        _locale: en|fr

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/admin
    requirements:
        _locale: en|fr


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
