# app/config/config.yml

jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        my_facebook_provider:
          id: my_user.facebook_provider # Notre provider, nous y viendrons par la suite.

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:    ^/(en|fr)/(login$|about|register|how|investors|media|resetting|invitation|set_locale/(en|fr))
            anonymous:  ~

        register_firewall:
            pattern:    ^/(register|resetting)
            anonymous:  ~

        secured_area:
            pattern:    ^/
            anonymous:  false
            form_login:
                login_path:   fos_user_security_login
                check_path:   fos_user_security_check
                default_target_path: clc_dashboard_homepage
                provider: fos_userbundle
                remember_me: true
            fos_facebook:
                app_url: "%api_facebook_name%"
                server_url: "%api_facebook_server%"
                check_path: _security_check   # Pour éviter toute confusion avec le formulaire de base, j'ai spécifié une route pour Facebook
                provider: my_facebook_provider
            remember_me:
                key: %secret%
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login

    access_control:
        - { path: ^/(en|fr)/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/about, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/how, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }