# app/config/config.yml

jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
      
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
            
        about_firewall:
            pattern:    ^/about$
            anonymous:  ~
            
        register_firewall:
            pattern:    ^/register
            anonymous:  ~

        how_firewall:
            pattern:    ^/how$
            anonymous:  ~
            
        resetting_firewall:
            pattern:    ^/resetting
            anonymous:  ~
            
        secured_area:
            pattern:    ^/
            anonymous:  false
            form_login:
                login_path:   /login
                check_path:   /login_check
                default_target_path: /
                provider: fos_userbundle
                remember_me: true
            remember_me:
                key: %secret%
            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/about$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/how$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }