<?php

namespace Clc\ColocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * invitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class invitationRepository extends EntityRepository
{
}
