# src/Clc/ShoppinglistBundle/Resources/config/routing.yml

clc_shoppinglist_homepage:
    pattern: /{state}
    defaults: { _controller: ClcShoppinglistBundle:Shoppinglist:index }

clc_shoppinglist_new:
    pattern: /
    defaults: { _controller: ClcShoppinglistBundle:Shoppinglist:new }

clc_shoppinglist_remove:
    pattern: /remove/{id}
    defaults: { _controller: ClcShoppinglistBundle:Shoppinglist:remove }
    
clc_shoppinglist_check:
    pattern: /check/{id}
    defaults: { _controller: ClcShoppinglistBundle:Shoppinglist:check }
    
clc_shoppinglist_uncheck:
    pattern: /uncheck/{id}
    defaults: { _controller: ClcShoppinglistBundle:Shoppinglist:uncheck }    
    
