parameters:
#    clc_shoppinglist.example.class: Clc\ShoppinglistBundle\Example

services:
    clc_shoppinglist.shoppinglist:
        class: Clc\ShoppinglistBundle\Services\Shoppinglist
        arguments: [@doctrine.orm.entity_manager]
