clc_welcome_login:
    pattern:  /login
    defaults: { _controller: ClcWelcomeBundle:Welcome:login}

clc_welcome_about:
    pattern:  /about
    defaults: { _controller: ClcWelcomeBundle:Welcome:about }

clc_welcome_register:
    pattern:  /register
    defaults: { _controller: ClcWelcomeBundle:Welcome:register }

clc_welcome_how:
    pattern:  /how
    defaults: { _controller: ClcWelcomeBundle:Welcome:how }

clc_welcome_investors:
    pattern:  /investors
    defaults: { _controller: ClcWelcomeBundle:Welcome:investors }

clc_welcome_media:
    pattern:  /media
    defaults: { _controller: ClcWelcomeBundle:Welcome:media }

clc_welcome_set_locale:
    pattern: /set_locale/{locale}
    defaults: { _controller: ClcWelcomeBundle:Welcome:setLocale }
