# src/Clc/ExpensemanagerBundle/Resources/config/routing.yml

clc_expensemanager_homepage:
    pattern: /
    defaults: { _controller: ClcExpensemanagerBundle:Expensemanager:index }
    
clc_expensemanager_new:
    pattern: /new
    defaults: { _controller: ClcExpensemanagerBundle:Expensemanager:new } 
    
clc_expensemanager_remove:
    pattern: /remove/{id}
    defaults: { _controller: ClcExpensemanagerBundle:Expensemanager:remove }
    
clc_expensemanager_applypayback:
    pattern: /payback
    defaults: { _controller: ClcExpensemanagerBundle:Expensemanager:applyPayback }