parameters:
#    clc_expensemanager.example.class: Clc\ExpensemanagerBundle\Example

services:
    clc_expensemanager.payback:
        class: Clc\ExpensemanagerBundle\Services\Payback
        arguments: [@clc_user.balance]
