parameters:
#    clc_expensemanager.example.class: Clc\ExpensemanagerBundle\Example

services:
#    clc_expensemanager.example:
#        class: %clc_expensemanager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
