clc_security_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ClcSecurityBundle:Default:index }
    
login:
    pattern:   /login
    defaults:  { _controller: ClcSecurityBundle:Security:login }
    
login_check:
    pattern:   /login_check
   
logout:
    pattern: /logout    
