parameters:
#    clc_security.example.class: Clc\SecurityBundle\Example

services:
#    clc_security.example:
#        class: %clc_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
