<?php

namespace Clc\TodosBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TodosController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Clc\TodosBundle\Controller\TodosController();
        return $instance;
    }
}
