clc_inbox_homepage:
    pattern:  /
    defaults: { _controller: ClcInboxBundle:Inbox:index }
    
clc_inbox_newmessage:
    pattern: /newmessage
    defaults: { _controller: ClcInboxBundle:Inbox:getMessageForm }
